### ISSUE TITLE
Update Source Dependency Link

### ISSUE THREAD

**Issue by dankoncs** [JeSuisUneLicorne/Connect4-Play#11]
Please consider updating the source dependency link inside the **build.sbt** file.

First, update your fork: https://github.com/JeSuisUneLicorne/HTWG_SE_ConnectFour

Then, update the source dependency link inside the **build.sbt** file.

**Comment by JeSuisUneLicorne** [comment]
Okay.

**Comment by JeSuisUneLicorne** [comment]
First, update your fork: https://github.com/JeSuisUneLicorne/HTWG_SE_ConnectFour -> Done.

Then, update the source dependency link inside the build.sbt file. -> wdym? where/which?

**Comment by JeSuisUneLicorne** [comment]
Done.
